package shared

import "core:math"

ARM_SCALE :: 1.2
ARM_INSET :: -0.1
CHEST_WIDTH :: 2.6

PLAYER_HEIGHT :: 11.0
LEG_HEIGHT :: 4.2
HEAD_SCALE :: 2.0

Game_Constants :: struct {
	billboard_count:                   i32,
	mouse_sensitivity:                 f32,
	world_uv_scale:                    f32,
	player_height:                     f32,
	border_height:                     f32,
	camera_height:                     f32,
	climb_height:                      f32,
	min_delta:                         f32,
	max_delta:                         f32,
	jump_velocity:                     f32,
	jump_aim_slow:                     f32,
	jump_push:                         f32,
	crouch_jump:                       f32,
	crouch_speed:                      f32,
	crouch_lean:                       f32,
	player_speed:                      f32,
	slipping_speed:                    f32,
	air_speed:                         f32,
	aim_slow:                          f32,
	crouch_slow:                       f32,
	player_slipping_jump_cooldown:     f32,
	terrain_slide_threshold:          f32,
	terrain_slip_decel:                f32,
	terrain_slide_decel:               f32,
	terrain_decel:                     f32,
	slide_decel:                       f32,
	air_decel:                         f32,
	ground_decel:                      f32,
	ladder_decel:                      f32,
	crouch_distance:                   f32,
	gravity:                           f32,
	arm_scale:                         f32,
	arm_inset:                         f32,
	chest_width:                       f32,
	chest_scale:                       f32,
	leg_scale:                         f32,
	leg_height:                        f32,
	head_scale:                        f32,
	body_height:                       f32,
	player_scale:                      f32,
	min_decel:                         f32,
	slide_time:                        f32,
	player_slide_velocity_mlt:         f32,
	player_terrain_slide_velocity_mlt: f32,
	idle_anim_speed:                   f32,
	interpolation:                     f32,
	lean_sensitivity:                  f32,
	lean_max:                          f32,
	lean_pull:                         f32,
	lean_pull_z:                       f32,
	lean_mlt_z:                        f32,
	bob_pull_y:                        f32,
	bob_pull_z:                        f32,
	bob_mlt_y:                         f32,
	bob_mlt_z:                         f32,
	crouch_anim:                       f32,
	collision_padding:                 f32,
	booster_speed:                     f32,
	ladder_speed:                      f32,
	ladder_scale:                      f32,
	ladder_width:                      f32,
	death_y:                           f32,
	recoil_mlt:                        f32,
	spread_adjustment:                 f32,
	upper_arm_length:                  f32,
	lower_arm_length:                  f32,
	arm_offset:                        f32,
	anim_mlt:                          f32,
	aim_anim_mlt:                      f32,
	crouch_anim_mlt:                   f32,
	step_anim:                         f32,
	step_pull:                         f32,
	disk_spin:                         f32,
}

GAME_CONSTANTS :: Game_Constants {
	billboard_count                   = 6,
	mouse_sensitivity                 = 0.0024,
	world_uv_scale                    = 60.0,
	player_height                     = PLAYER_HEIGHT,
	border_height                     = 250.0,
	camera_height                     = 1.5,
	climb_height                      = 3.0,
	min_delta                         = 0.0001,
	max_delta                         = 0.033,
	jump_velocity                     = 0.072,
	jump_aim_slow                     = 0.85,
	jump_push                         = 0.1,
	crouch_jump                       = 0.25,
	crouch_speed                      = 7.0,
	crouch_lean                       = math.PI * -0.1,
	player_speed                      = 0.42,
	slipping_speed                    = 0.3,
	air_speed                         = 0.047,
	aim_slow                          = 0.55,
	crouch_slow                       = 0.3,
	player_slipping_jump_cooldown     = 0.5,
	terrain_slide_threshold          = 1.9,
	terrain_slip_decel                = 0.99,
	terrain_slide_decel               = 0.9996,
	terrain_decel                     = 0.99,
	slide_decel                       = 0.999,
	air_decel                         = 0.9996,
	ground_decel                      = 0.99,
	ladder_decel                      = 0.97,
	crouch_distance                   = 3.0,
	gravity                           = 0.15,
	arm_scale                         = ARM_SCALE,
	arm_inset                         = ARM_INSET,
	chest_width                       = CHEST_WIDTH,
	chest_scale                       = 1.3,
	leg_scale                         = 1.3,
	leg_height                        = LEG_HEIGHT,
	head_scale                        = HEAD_SCALE,
	body_height                       = PLAYER_HEIGHT - HEAD_SCALE - LEG_HEIGHT,
	player_scale                      = (ARM_SCALE * 2.0 + CHEST_WIDTH + ARM_INSET) * 0.5,
	min_decel                         = 0.0001,
	slide_time                        = 0.35,
	player_slide_velocity_mlt         = 1.2,
	player_terrain_slide_velocity_mlt = 0.4,
	idle_anim_speed                   = 1.5,
	interpolation                     = 1.1,
	lean_sensitivity                  = 0.05,
	lean_max                          = 0.16,
	lean_pull                         = 0.99,
	lean_pull_z                       = 0.99,
	lean_mlt_z                        = 0.03,
	bob_pull_y                        = 0.985,
	bob_pull_z                        = 0.99,
	bob_mlt_y                         = 0.024,
	bob_mlt_z                         = 0.02,
	crouch_anim                       = 0.8,
	collision_padding                 = 1.1,
	booster_speed                     = 2.0,
	ladder_speed                      = 35.0,
	ladder_scale                      = 0.5,
	ladder_width                      = 3.2,
	death_y                           = -100.0,
	recoil_mlt                        = 0.3,
	spread_adjustment                 = 0.00063,
	upper_arm_length                  = 2.7,
	lower_arm_length                  = 2.7,
	arm_offset                        = -0.8,
	anim_mlt                          = 1.2,
	aim_anim_mlt                      = 0.18,
	crouch_anim_mlt                   = 0.5,
	step_anim                         = 0.075,
	step_pull                         = 0.995,
	disk_spin                         = 0.2,
}
