package shared

import "core:math/linalg"
import "core:encoding/json"

Vec2 :: linalg.Vector2f32
Vec3 :: linalg.Vector3f32
Vec4 :: linalg.Vector4f32
Mat4 :: linalg.Matrix4f32

Prefab :: enum {
	CUBE,
	CRATE,
	BARREL,
	LADDER,
	PLANE,
	SPAWN_POINT,
	CAMERA_POSITION,
	VEHICLE,
	STACK,
	RAMP,
	SCORE_ZONE,
	BILLBOARD,
	DEATH_ZONE,
	PARTICLES,
	OBJECTIVE,
	TREE,
	CONE,
	CONTAINER,
	GRASS,
	CONTAINER_R,
	ACID_BARREL,
	DOOR,
	WINDOW,
	FLAG,
	GATE,
	CHECK_POINT,
	WEAPON_PICKUP,
	TELEPORTER,
	TEDDY,
	TRIGGER,
	SIGN,
	DEPOSIT_BOX,
	LIGHT_CONE,
	SPECTATE_CAM,
	SPHERE,
	PLACEHOLDER,
	CARD_B,
	PALLET,
	LIQUID,
	SOUND_EMITTER,
	EVENT,
	TERMINAL,
	PREMIUM_ZONE,
	VERIFIED_ZONE,
	CUSTOM_ASSET,
	BOMB_SITE,
	BOOST_PAD,
	TEAM_ZONE,
	CYLINDER,
	POLICE,
	CAGE,
	E_BARREL,
	SHOWCASE,
	POINT_LIGHT,
	GHOST,
	BOT,
	PUMPKIN,
	RUNE,
	SKELETON,
	KNIGHT,
}

Collision_Type :: enum {
	BOX,
	CYLINDER,
	NONE,
}

Camera_Type :: enum {
	NORMAL,
	TOP_DOWN,
	PLATFORMER_X,
	PLATFORMER_Z,
}

Model_Type :: enum {
	NORMAL,
	SPRITE,
}

Team_Options :: enum {
	NONE,
	HIDERS,
	SEEKERS,
	SURVIVORS,
	INFECTED,
	FOLLOWERS,
	SIMON,
	PROP,
	HEROES,
	BOSS,
	LIVING,
	STALKER,
	INNOCENT,
	TRAITOR,
}

Ramp :: struct {
	boost: f32,
	start: Vec2,
	end:   Vec2,
}

Texture_Animation :: struct {
	move:           f32,
	move_direction: i32,
	frames:         i32,
	frame_time:     f32,
}

Object :: struct {
	prefab:         Prefab,
	texture:        u32,
	active:         bool,
	is_border:      bool,
	premium:        bool,
	verified:       bool,
	jump_pad:       bool,
	team_zone:      bool,
	score_zone:     bool,
	teleporter:     bool,
	checkpoint:     bool,
	pickup:         bool,
	flag:           bool,
	trigger:        bool,
	kill:           bool,
	objective:      bool,
	bomb_site:      bool,
	spawnable:      bool,
	crouch:         bool,
	ladder:         bool,
	wall_jumpable:  bool,
	direction:      u8,
	team:           u32,
	score_points:   u32,
	spin:           f32,
	bounce:         f32,
	collision_type: Collision_Type,
	position:       Vec3,
	scale:          Vec3,
	tex_anim:       ^Texture_Animation,
	ramp:           ^Ramp,
	mesh:           rawptr,
	raw_data:       json.Value,
}

Spawn :: struct {
	position:  Vec3,
	team:      i32,
	direction: i32,
	comp:      i32,
}

Map_Config :: struct {
	cam_type:       Camera_Type,
	cam_rotation:   bool,
	cam_offset:     Vec3,
	model:          Model_Type,
	speed:          Vec3,
	ladder_accel:   f32,
	air_accel:      f32,
	slide_time:     f32,
	slide_accel:    f32,
	jump_cooldown:  f32,
	infinite_jump: bool,
}

Map :: struct {
	config:          Map_Config,
	death_y:         f32,
	spawns:          [dynamic]^Spawn,
	objects:         [dynamic]^Object,
	min_dim:         Vec3,
	max_dim:         Vec3,
	camera_position: Vec3,
	raw_data:        json.Value, // Keeps the parse tree alive for the client.
	colors:          []Vec4,
}

Class_Config :: struct {
	name:            string,
	icon_index:      i32,
	texts:           []string,
	loadout:         []i32,
	secondary:       bool,
	wall_jump:       bool,
	colors:          [6]i32,
	health:          i32,
	health_segments: i32,
	regen:           f32,
	speed:           f32,
}

Input :: struct {
	seq:      i32,
	move_dir: i32,
	delta:    f32,
	x_dir:    f32,
	y_dir:    f32,
	shoot:    bool,
	scope:    bool,
	jump:     bool,
	crouch:   bool,
	reload:   bool,
	swap:     u8,
}

Player_Skins :: struct {
	primary:    i32,
	secondary:  i32,
	face:       i32,
	hat:        i32,
	back:       i32,
	waist:      i32,
	melee:      i32,
	dye:        i32,
	skin_color: i32,
	hair_color: i32,
}

Weapon :: struct {
	name:                  string,
	src:                   string,
	icon:                  string,
	model:                 string,
	texture:               string,
	sound:                 string,
	secondary:             bool,
	no_spread:             bool,
	akimbo:                bool,
	no_aim:                bool,
	no_auto:               bool,
	no_inspect:            bool,
	can_throw:             bool,
	melee:                 bool,
	equipment:             bool,
	bomb:                  bool,
	burst:                 bool,
	projectile:            bool,
	projectile_disable:    bool,
	animate_while_aiming:  bool,
	burst_count:           u32,
	burst_rate:            f32,
	ammo:                  u32,
	shots:                 u32,
	swap_time:             f32,
	reload_time:           f32,
	aim_speed:             f32,
	speed_mlt:             f32,
	jump_mlt:              f32,
	damage:                f32,
	headshot_mlt:          f32,
	pierce:                f32,
	range:                 f32,
	drop_start:            f32,
	damage_drop:           f32,
	rate:                  f32,
	spread:                f32,
	min_spread:            f32,
	recoil:                f32,
	recoil_y:              f32,
	recoil_r:              f32,
	recover:               f32,
	recover_y:             f32,
	recover_f:             f32,
	physical_power:        f32,
	physical_range:        f32,
	zoom:                  f32,
	inaccuracy:            f32,
	recoil_y_mlt:          f32,
	recoil_z:              f32,
	recoil_z_mlt:          f32,
	rotation:              f32,
	z_rotation:            f32,
	z_rotation_mlt:        f32,
	z_lean_mlt:            f32,
	y_rotation:            f32,
	rotation_offset:       f32,
	rotation_offset_aim:   f32,
	jump_y_mlt:            f32,
	land_bob:              f32,
	aim_recoil_mlt:        f32,
	lean_mlt:              f32,
	inspect_rotation:      f32,
	inspect_mlt:           f32,
	crouch_lean:           f32,
	crouch_rotation:       f32,
	crouch_drop:           f32,
	scale:                 f32,
	hold_width:            f32,
	hold_distance_offset:  f32,
	origin:                Vec3,
	offset:                Vec3,
	left_hold:             Vec3,
	right_hold:            Vec3,
	custom_spread:         []Vec2,
}

Player :: struct {
	game:                            ^Game,
	uid:                             i32,
	is_you:                          bool,
	render_you:                      bool,
	left_handed:                     bool,
	active:                          bool,
	noclip:                          bool,
	god_mode:                        bool,
	unlimited_ammo:                  bool,
	force_hide:                      bool,
	interpolate:                     bool,
	inspecting:                      bool,
	is_hidden:                       bool,
	on_ground:                       bool,
	on_ladder:                       bool,
	on_ramp:                         bool,
	on_terrain:                      bool,
	on_wall:                         u8,
	terrain_slipping:                bool,
	wall_jump:                       bool,
	did_act:                         bool,
	did_shoot:                       bool,
	did_jump:                        bool,
	did_wall_jump:                   bool,
	can_slide:                       bool,
	can_throw:                       bool,
	kills:                           u32,
	deaths:                          u32,
	death_streak:                    u32,
	score:                           u32,
	input_seq:                       i32,
	dt:                              f32,
	send_rate:                       f32,
	interp_pos_start:                Vec3,
	interp_pos_end:                  Vec3,
	interp_dir_start:                Vec2,
	interp_dir_end:                  Vec2,
	health:                          f32,
	max_health:                      i32,
	last_damage_time:                f32,
	respawn_timer:                   f32,
	team:                            i32,
	class_index:                     i32,
	scale:                           f32,
	height:                          f32,
	speed:                           f32,
	spread:                          f32,
	crouch_val:                      f32,
	aim_val:                         f32,
	aim_time:                        f32,
	slid_cont:                       i32,
	air_time:                        f32,
	covered_distance:                f32,
	swap_timer:                      f32,
	reload_timer:                    f32,
	slide_timer:                     f32,
	jump_timer:                      f32,
	interact_progress:               f32,
	ramp_fix:                        ^f32,
	idle_anim:                       f32,
	hp_chase:                        f32,
	position:                        Vec3,
	last_position:                   Vec3,
	velocity:                        Vec3,
	direction:                       Vec2,
	x_vel_cylinder:                  f32,
	z_vel_cylinder:                  f32,
	jump_rotate:                     f32,
	land_bob_y:                      f32,
	land_bob_yr:                     f32,
	jump_bob_y:                      f32,
	jump_rotate_mlt:                 f32,
	step_val:                        f32,
	step_chase:                      f32,
	bob_anim:                        Vec3,
	lean_anim:                       Vec3,
	recoil:                          Vec3,
	recoil_force:                    f32,
	recoil_anim:                     f32,
	recoil_anim_y:                   f32,
	loadout:                         []i32,
	ammo:                            []u32,
	reloads:                         []f32,
	burst_count:                     i32,
	loadout_size:                    i32,
	loadout_index:                   i32,
	input_queue:                     [dynamic]Input,
	weapon:                          ^Weapon,
	skins:                           Player_Skins,
	mesh:                            rawptr,
}

Game_Config :: struct {
	tick_rate:          i32,
	max_players:        i32,
	min_players:        i32,
	game_time:          i32,
	warmup_time:        f32,
	auto_respawn:       i32,
	lives:              i32,
	score_limit:        i32,
	gravity_mlt:         f32,
	jump_mlt:            f32,
	delta_mlt:           f32,
	slide_time:         f32,
	impulse_mlt:        f32,
	wall_jump:          f32,
	strafe_speed:       f32,
	can_slide:          bool,
	air_strafe:         bool,
	auto_jump:          bool,
	bullet_drop:        bool,
	health_regen:       bool,
	kill_rewards:       bool,
	headshots_only:     bool,
	no_secondaries:     bool,
	no_streaks:         bool,
	disable_borders:    bool,
	throwable_melees:   bool,
	select_team:        bool,
	allow_spectate:     bool,
	third_person:       bool,
	hide_nametags:      bool,
	team1_name:         string,
	team2_name:         string,
	team1_damage:       f32,
	team2_damage:       f32,
	health_mlt:         f32,
	fire_rate:          f32,
	reload_speed:       f32,
	objective_rotation_time: f32,
	objective_score_rate:    f32,
	regen_delay:             f32,
	respawn_delay:           f32,
	maps:               []i32,
	modes:              []i32,
}

Player_Kill_Info :: struct {
	streak:    i32,
	weapon_id: i32,
}

Bullet_Impact :: struct {
	position: Vec3,
	normal:   Vec3,
}

Vote_Kick :: struct {
	timer:     f32,
	votes_for: i32,
	votes_req: i32,
	player:    ^Player,
}

Game_Mode_Config :: struct {
	real_movement:         bool,
	no_weapons:            bool,
	no_regen:              bool,
	no_reloads:            bool,
	no_pickups:            bool,
	no_streaks:            bool,
	no_clan:               bool,
	teams:                 bool,
	dmg_team:              bool,
	site:                  bool,
	flags:                 bool,
	convert_team:          bool,
	kill_on_convert:       bool,
	friendly:              bool,
	clan_war:              bool,
	starting_loadout:      []i32,
	team_class:            [3]i32,
	speed_mlt:             [3]f32,
	force_class:           i32,
	health:                i32,
	lives:                 i32,
	ammo_limit:            i32,
	hitbox_pad:            f32,
}

Game_Mode :: struct {
	config:     Game_Mode_Config,
	objective:  bool,
}

Free_For_All :: struct {
	using mode: Game_Mode,
}

Match_Phase :: enum u8 {
	WARMUP,
	LIVE,
	ENDED,
}

Objective_State :: struct {
	active_object_index: i32,
	active_zone:         i32,
	owner_team:          i32,
	contested:           bool,
	rotation_remaining:  f32,
	score_accumulator:   f32,
}

Match_State :: struct {
	phase:          Match_Phase,
	phase_remaining: f32,
	time_remaining: f32,
	team_scores:    [3]u32,
	objective:      Objective_State,
}

Game :: struct {
	config:       Game_Config,
	map_inst:     ^Map,
	mode:         ^Game_Mode,
	weapons:      []^Weapon,
	classes:      []Class_Config,
	maps_list:    []^Map,
	maps_list_owned: bool,
	map_count:    i32,
	modes_list:   []i32,
	mode_count:   i32,
	current_map_index: i32,
	player_count: i32,
	players:      [dynamic]^Player,
	impacts:      [dynamic]Bullet_Impact,
	objective_indices: [dynamic]i32,
	match:        Match_State,
	now:          f32,
	move_lock:    bool,
	is_local:     bool,
	ready:        bool,
	end_timer:    f32,
	nuke_timer:   f32,
	nuke_player:  ^Player,
	vote_kick:    ^Vote_Kick,
	server:       rawptr,
}

DEFAULT_GAME_CONFIG :: Game_Config {
	tick_rate       = 64,
	max_players     = 2,
	min_players     = 0,
	game_time       = 4,
	warmup_time     = 0.0,
	auto_respawn    = 1,
	lives           = 0,
	score_limit     = 250,
	gravity_mlt     = 1.0,
	jump_mlt        = 1.0,
	delta_mlt       = 1.0,
	slide_time      = 1.0,
	impulse_mlt     = 1.0,
	wall_jump       = 1.0,
	strafe_speed    = 1.2,
	can_slide       = true,
	air_strafe      = false,
	auto_jump       = false,
	bullet_drop     = false,
	health_regen    = true,
	kill_rewards    = true,
	headshots_only  = false,
	no_secondaries  = false,
	no_streaks      = false,
	disable_borders = false,
	throwable_melees = true,
	select_team     = false,
	allow_spectate  = true,
	third_person    = false,
	hide_nametags   = false,
	team1_name      = "Team 1",
	team2_name      = "Team 2",
	team1_damage    = 1.0,
	team2_damage    = 1.0,
	health_mlt      = 1.0,
	fire_rate       = 1.0,
	reload_speed    = 1.0,
	objective_rotation_time = 60.0,
	objective_score_rate    = 1.0,
	regen_delay             = 5.0,
	respawn_delay           = 3.0,
}
